services:
  backend:
    build: ./backend
    container_name: t1d-model-deployment-backend
    ports:
      - "3001:3001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 3001

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
    container_name: t1d-model-deployment-frontend
    ports:
      - "4000:4000"
